#!/usr/bin/env python3
"""Convert chardet 7 CP1250/CP1252 bigram profiles into Pascal constants.

Usage: python3 tests/generate-windows1250-models.py /path/to/chardet-7
"""

import hashlib
import struct
import subprocess
import sys
import zlib
from pathlib import Path

SOURCE_REVISION = "e9603fad69cdc5d34d03616682650acd4891eb5d"


def read_models(path):
    data = path.read_bytes()
    if data[:4] != b"CMD2":
        raise ValueError("Expected chardet CMD2 models.bin")
    count = struct.unpack_from(">I", data, 4)[0]
    offset = 8
    header = []
    for _ in range(count):
        length = struct.unpack_from(">I", data, offset)[0]
        offset += 4
        name = data[offset : offset + length].decode("utf-8")
        offset += length
        norm = struct.unpack_from(">d", data, offset)[0]
        offset += 8
        header.append((name, norm))
    tables = zlib.decompress(data[offset:])
    if len(tables) != count * 65536:
        raise ValueError("Unexpected model table length")
    return [(name, norm, tables[i * 65536 : (i + 1) * 65536])
            for i, (name, norm) in enumerate(header)]


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    root = Path(sys.argv[1]).resolve()
    model_dir = root / "src/chardet/models"
    model_path = model_dir / "models.bin"
    idf_path = model_dir / "idf.bin"
    idf = idf_path.read_bytes()
    if len(idf) != 65536:
        raise ValueError("Unexpected IDF table length")
    revision = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=root, text=True
    ).strip()
    if revision != SOURCE_REVISION:
        raise ValueError(f"Expected chardet revision {SOURCE_REVISION}, got {revision}")
    models = [(name, norm, table) for name, norm, table
              in read_models(model_path)
              if name.endswith(("/cp1250", "/cp1252"))]
    entries = []
    descriptors = []
    for name, norm, table in models:
        start = len(entries)
        entries.extend((pair, weight * idf[pair])
                       for pair, weight in enumerate(table) if weight)
        charset = ("WINDOWS_1250_CHARSET" if name.endswith("/cp1250")
                   else "WINDOWS_1252_CHARSET")
        descriptors.append((name, charset, start, len(entries) - start, norm))

    output = Path(__file__).resolve().parents[1] / "src/sbseq/CharsetWindows1250Models.inc"
    with output.open("w", encoding="ascii", newline="\n") as out:
        out.write("{ Generated by tests/generate-windows1250-models.py.\n")
        out.write("  SPDX-License-Identifier: 0BSD\n")
        out.write(f"  Source: https://github.com/chardet/chardet commit {revision}\n")
        out.write(f"  models.bin SHA-256: {hashlib.sha256(model_path.read_bytes()).hexdigest()}\n")
        out.write(f"  idf.bin SHA-256: {hashlib.sha256(idf).hexdigest()}\n")
        out.write("  Copyright (c) 2026 Dan Blanchard.\n")
        out.write("  Full license: LICENSES/0BSD.txt.\n")
        out.write("  Only CP1250 and CP1252 profiles are included.\n}\n")
        out.write(f"const ModelCount = {len(descriptors)};\n")
        out.write(f"const EntryCount = {len(entries)};\n")
        out.write("const ModelInfo: array[0..ModelCount - 1] of TModelInfo = (\n")
        for i, (name, charset, start, length, norm) in enumerate(descriptors):
            end = "," if i + 1 < len(descriptors) else ""
            out.write(f"  (Charset: {charset}; First: {start}; Count: {length}; "
                      f"Norm: {norm:.17g}){end} {{ {name} }}\n")
        out.write(");\n")
        for label, values in (
            ("ModelPairs", [pair for pair, _ in entries]),
            ("ModelWeights", [value for _, value in entries]),
        ):
            out.write(f"const {label}: array[0..EntryCount - 1] of Word = (\n")
            for i in range(0, len(values), 16):
                line = ", ".join(str(value) for value in values[i : i + 16])
                end = "," if i + 16 < len(values) else ""
                out.write(f"  {line}{end}\n")
            out.write(");\n")
        out.write("const IDFWeights: array[0..65535] of Byte = (\n")
        for i in range(0, len(idf), 32):
            line = ", ".join(str(value) for value in idf[i : i + 32])
            end = "," if i + 32 < len(idf) else ""
            out.write(f"  {line}{end}\n")
        out.write(");\n")
    print(f"{output}: {len(models)} models, {len(entries)} nonzero pairs")


if __name__ == "__main__":
    main()
